/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function macClear(): void
export function macGet(format: string): Buffer
export function macSet(format: string, data: Buffer): boolean
