/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function clipRead(): string
export function clipWrite(s: string): void
export function mozjpegTest(width: number, height: number, buf: Buffer): Buffer
export function test(): Buffer
export function test2(format: string, data: Buffer): void
